<x-flatpack-layout>
    <livewire:flatpack.form
        :model="$model"
        :entity="$entity"
        :entry="$entry"
        :composition="$composition"
        :formType="$formType"
        />
</x-flatpack-layout>
