import type { LucideIcon } from 'lucide-react';
import {
    Activity,
    Archive,
    ArrowRight,
    Award,
    BarChart3,
    Bell,
    Book,
    Bookmark,
    BookOpen,
    Box,
    Briefcase,
    Building,
    Building2,
    Calendar,
    CalendarDays,
    ChartColumn,
    ChartPie,
    Check,
    ChevronRight,
    Clipboard,
    Clock,
    Cloud,
    Code,
    Cog,
    Command,
    Copy,
    CreditCard,
    Database,
    Download,
    ExternalLink,
    Eye,
    File,
    Files,
    FileText,
    Filter,
    Flag,
    Folder,
    FolderCheck,
    FolderClock,
    FolderClosed,
    FolderCode,
    FolderCog,
    FolderOpen,
    Folders,
    Gift,
    Globe,
    HardDrive,
    Heart,
    HelpCircle,
    Home,
    Image,
    Images,
    Inbox,
    Info,
    Key,
    Layers,
    LayoutDashboard,
    LayoutGrid,
    LayoutList,
    LineChart,
    Link,
    List,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map as MapIcon,
    MapPin,
    Menu,
    MessageSquare,
    MessagesSquare,
    Minus,
    Monitor,
    Moon,
    MoreHorizontal,
    Package,
    Palette,
    Pencil,
    Phone,
    Plus,
    Rocket,
    Search,
    Send,
    Settings,
    Shield,
    ShoppingCart,
    Smartphone,
    Sparkles,
    SquarePen,
    Star,
    Sun,
    Table,
    Tag,
    Tags,
    Terminal,
    Trash2,
    TrendingDown,
    TrendingUp,
    Truck,
    Upload,
    User,
    UserCog,
    UserPlus,
    Users,
    Wallet,
    Wrench,
    X,
    Zap,
} from 'lucide-react';

/**
 * Icons for menu `icon` strings from Laravel (`LucideIconByName`).
 * Keys are Lucide kebab-case names; extend when adding entries in `config/flatpack.php` (or host config).
 */
export const flatpackMenuIcons = {
    activity: Activity,
    archive: Archive,
    'arrow-right': ArrowRight,
    award: Award,
    'bar-chart': BarChart3,
    bell: Bell,
    book: Book,
    'book-open': BookOpen,
    bookmark: Bookmark,
    box: Box,
    briefcase: Briefcase,
    building: Building,
    'building-2': Building2,
    calendar: Calendar,
    'calendar-days': CalendarDays,
    'chart-bar': ChartColumn,
    'chart-line': LineChart,
    'chart-pie': ChartPie,
    check: Check,
    'chevron-right': ChevronRight,
    clipboard: Clipboard,
    clock: Clock,
    cloud: Cloud,
    code: Code,
    cog: Cog,
    command: Command,
    copy: Copy,
    'credit-card': CreditCard,
    database: Database,
    download: Download,
    edit: SquarePen,
    ellipsis: MoreHorizontal,
    'external-link': ExternalLink,
    eye: Eye,
    file: File,
    'file-text': FileText,
    files: Files,
    filter: Filter,
    flag: Flag,
    folder: Folder,
    'folder-check': FolderCheck,
    'folder-clock': FolderClock,
    'folder-closed': FolderClosed,
    'folder-code': FolderCode,
    'folder-cog': FolderCog,
    'folder-open': FolderOpen,
    folders: Folders,
    gift: Gift,
    globe: Globe,
    grid: LayoutGrid,
    'hard-drive': HardDrive,
    heart: Heart,
    'help-circle': HelpCircle,
    home: Home,
    image: Image,
    images: Images,
    inbox: Inbox,
    info: Info,
    key: Key,
    layer: Layers,
    layers: Layers,
    'layout-dashboard': LayoutDashboard,
    'layout-grid': LayoutGrid,
    'layout-list': LayoutList,
    link: Link,
    list: List,
    lock: Lock,
    'log-in': LogIn,
    'log-out': LogOut,
    mail: Mail,
    map: MapIcon,
    'map-pin': MapPin,
    menu: Menu,
    'message-square': MessageSquare,
    'messages-square': MessagesSquare,
    minus: Minus,
    monitor: Monitor,
    moon: Moon,
    package: Package,
    palette: Palette,
    pencil: Pencil,
    phone: Phone,
    plus: Plus,
    rocket: Rocket,
    search: Search,
    send: Send,
    settings: Settings,
    shield: Shield,
    'shopping-cart': ShoppingCart,
    smartphone: Smartphone,
    sparkles: Sparkles,
    star: Star,
    sun: Sun,
    table: Table,
    tag: Tag,
    tags: Tags,
    terminal: Terminal,
    trash: Trash2,
    'trending-down': TrendingDown,
    'trending-up': TrendingUp,
    truck: Truck,
    upload: Upload,
    user: User,
    'user-cog': UserCog,
    'user-plus': UserPlus,
    users: Users,
    wallet: Wallet,
    wrench: Wrench,
    x: X,
    zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type FlatpackMenuIconName = keyof typeof flatpackMenuIcons;
